---
author: "Mert Bildirici"
title: "First Project"
date: 03/08/2023
---
```{r}
install.packages("ggimage")
```

```{r}
library(tidyverse)
library(fivethirtyeight)
library(plotly)
library(ggimage)
```

```{r}
advanced = read_csv("data/advanced_stats.csv")
```

```{r}
advanced|>
  plot_ly(x = ~ Season,
         y = ~ `TOV%`,
         z = ~ `AST%`,
         color = ~ Player,
         type = "scatter3d",
         mode = "markers")

```


```{r}
# Cumulative lines animation
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])})
    
  dplyr::bind_rows(dats)
}

# Axis labels
abbrev_x_jordan <- c("1984-85", "1985-86", "1986-87", "1987-88", "1988-89",
                     "1989-90", "1990-91", "1991-92", "1992-93", "1994-95",
                     "1995-96", "1996-97", "1997-98", "2001-02", "2002-03")

# Michael Jordan stats (1984-2003) - Points, Rebounds and Assists per game. Regular Season and Playoffs
plot <- advanced %>%
  filter(Player=="Michael Jordan") %>%
  select(Season, PER, `STL%`, `AST%`, `BLK%`) %>%
  mutate(Season=as.numeric(substr(Season, 1, 4))) %>%
  gather(Stats, Value, 2:4) %>%
  accumulate_by(~Season) %>%
  ggplot(aes(x=Season, y=Value, colour= "blue", group="blue", frame=frame)) +
  geom_line(size=1) +
  geom_point() +
  facet_grid(Stats ~ . , scales="free") +
  labs(title="Michael Jordan stats (1984-2003)
       Points, Rebounds and Assists per game. Regular Season and Playoffs") +
  scale_x_continuous(breaks=c(1984:1992, 1994:1997, 2001, 2002), labels=abbrev_x_jordan) +
  theme_bw() +
  theme(axis.title.y=element_blank(), 
        axis.title.x=element_blank(), 
        axis.text.x=element_text(angle=45, hjust=1)) 

# Create plotly graph
ggplotly(plot, height=600, width=900, tooltip=c("x", "y", "colour", "frame")) %>%
  animation_slider(hide=T) %>%
  layout(xaxis=list(title="Season"), showlegend=FALSE)
```



```{r}
# Cumulative lines animation
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])})
    
  dplyr::bind_rows(dats)
}

advanced_lebron_moving <- advanced |>
  filter(Player == "Lebron James" & RSorPO == "Regular Season")

# Axis labels

abbrev_x_lebron <- c("2003-2004", "2004-2005", "2005-2006", "2006-2007", 
                     "2007-2008", "2008-2009", "2009-2010", "2010-2011",
                     "2011-2012", "2012-2013", "2013-2014", "2014-2015",
                     "2015-2016", "2016-2017", "2017-2018", "2018-2019")

# Michael Jordan stats (1984-2003) - Points, Rebounds and Assists per game. Regular Season and Playoffs
lebronplot <- advanced_lebron_moving %>%
  select(Season, PER, `STL%`, `AST%`, `BLK%`) %>%
  gather(Stats, Value, 2:4) %>%
  accumulate_by(~Season) %>%
  ggplot(aes(x=Season, y=Value, group="blue", frame=frame)) +
  geom_line(size=1, color = "blue") +
  geom_point() +
  facet_grid(Stats ~ . , scales="free") +
  labs(title="Lebron James Stats") +
  scale_x_discrete(breaks=c(2003:2018), labels = abbrev_x_lebron) +
  theme_bw() +
  theme(axis.title.y=element_blank(), 
        axis.title.x=element_blank(), 
        axis.text.x=element_text(angle=45, hjust=1))

# Create plotly graph
ggplotly(lebronplot, height=600, width=900, tooltip=c("x", "y", "colour", "frame")) %>%
  animation_slider(hide=T, frameRate = 2) %>%
  layout(xaxis=list(title="Season"), showlegend=TRUE)
```
